"""Add fuel tracking columns

Revision ID: 6ccf83d8600c
Revises: 84cbbed91ebb
Create Date: 2025-08-18 11:48:59.467950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ccf83d8600c'
down_revision = '84cbbed91ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns to fill_up table
    with op.batch_alter_table('fill_up', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_full_tank', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('fuel_before_fillup', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fill_up', schema=None) as batch_op:
        batch_op.drop_column('fuel_before_fillup')
        batch_op.drop_column('is_full_tank')
    # ### end Alembic commands ###
