"""Add fuel_type column to Vehicle model

Revision ID: add_fuel_type
Revises: 6ccf83d8600c
Create Date: 2026-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = 'add_fuel_type'
down_revision = '6ccf83d8600c'
branch_labels = None
depends_on = None


def upgrade():
    # commands auto generated by Alembic 
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_type', sa.String(50), nullable=False, server_default='Petrol'))

    # end commands 


def downgrade():
    # commands auto generated by Alembic 
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('fuel_type')
    # end Alembic commands 
